### ISSUE TITLE
Dépendance sur la version 3.18 CMake obligatoire ?

### ISSUE THREAD

**Issue by pcotret** [EVEEX-Project/EVEEX-Code#64]
https://github.com/EVEEX-Project/EVEEX-Code/blob/master/c_prototype/CMakeLists.txt#L1

Y'a une raison particulière à avoir une dépendance sur la version 3.18 de Cmake ?
Possibilité de mettre une version un peu moins récente ?

Config perso :
- Ubuntu 20 LTS
- CMake 3.16

**Comment by NightlySide** [comment]
Aucune raison particulière autre que c'est la version installée par défaut chez moi...

Config perso :

- Manjaro avec kernel 5.9.11-3
- CMake 3.18

Je l'ai ajusté et cela ne devrait pas poser de problèmes !
